last_change = 2026-09-24T17:36:02.019941Z
addr = 0x9f580
size = 0x8
name = "CNetworkMessages_IsAdditionalMessageRegistrationAllowed"
type = "long long"

[header]
name = "CNetworkMessages_IsAdditionalMessageRegistrationAllowed"
addr = 0x9f580
type = "long long"

[header.args]
