last_change = 2026-09-24T17:36:02.965907Z
addr = 0xdddd0
size = 0x1bd
name = "CNetworkMessages_AssociateNetMessageGroupIdWithChannelCategory"
type = "long long"

[header]
name = "CNetworkMessages_AssociateNetMessageGroupIdWithChannelCategory"
addr = 0xdddd0
type = "long long"

[header.args]
