last_change = 2026-09-24T17:36:02.969802Z
addr = 0xdee10
size = 0x2db
name = "CNetworkMessages_RegisterNetworkFieldSerializer"
type = "long long"

[header]
name = "CNetworkMessages_RegisterNetworkFieldSerializer"
addr = 0xdee10
type = "long long"

[header.args]
