last_change = 2026-09-24T17:36:03.012086Z
addr = 0xe0db0
size = 0x124
name = "CNetworkMessages_FindNetworkGroup"
type = "long long"

[header]
name = "CNetworkMessages_FindNetworkGroup"
addr = 0xe0db0
type = "long long"

[header.args]
