last_change = 2026-09-24T17:36:02.019990Z
addr = 0xe0c80
size = 0x57
name = "CNetworkMessages_DeallocateNetMessageAbstract"
type = "void"

[header]
name = "CNetworkMessages_DeallocateNetMessageAbstract"
addr = 0xe0c80
type = "void"

[header.args]
