last_change = 2026-09-24T17:36:02.019987Z
addr = 0xe0c30
size = 0x4b
name = "CNetworkMessages_AllocateAndCopyConstructNetMessageAbstract"
type = "long long"

[header]
name = "CNetworkMessages_AllocateAndCopyConstructNetMessageAbstract"
addr = 0xe0c30
type = "long long"

[header.args]
