last_change = 2026-09-24T17:36:02.020009Z
addr = 0xf6c60
size = 0x2b3
name = "CNetworkSystem_CloseAllSockets"
type = "long long"

[header]
name = "CNetworkSystem_CloseAllSockets"
addr = 0xf6c60
type = "long long"

[header.args]
