last_change = 2026-09-24T17:36:03.077248Z
addr = 0xfb0b0
size = 0x8fb
name = "CNetworkSystem_SendNetworkStats"
type = "void"

[header]
name = "CNetworkSystem_SendNetworkStats"
addr = 0xfb0b0
type = "void"

[header.args]
