last_change = 2026-09-24T17:36:03.050416Z
addr = 0xf6f20
size = 0x43a
name = "CNetworkSystem_OpenSocket"
type = "bool"

[header]
name = "CNetworkSystem_OpenSocket"
addr = 0xf6f20
type = "bool"

[header.args]
